### ISSUE TITLE
vat rate

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#17]
Could you use 21.00% as default for item creation until #16 is done?

**Comment by cghislai** [comment]
Fixed in frontend master.

Looks like I cant close issues ? Nor even assign them to myself?

**Comment by ymajoros** [comment]
You just did, so I guess it's ok now. Seems I still can't assign to you, though.

**Comment by cghislai** [comment]
i think its cause I opened this one
